### ISSUE TITLE
Container width $xl-media

### ISSUE THREAD

**Issue by einar-hjortdal** [HimasRafeek/butterCake#9]
Hi,
In the compiled CSS the `.container` class does not use the 1260px breakpoint

```css
.container {
    margin: 0 auto;
    padding-left: 10px;
    padding-right: 10px;
    width: 100%;
    /* Breakpoints | Min Width */
}

@media (min-width: 590px) {
    .container {
        max-width: calc(100% - 50px);
    }
}

@media (min-width: 790px) {
    .container {
        max-width: calc(100% - 100px);
    }
}

@media (min-width: 1160px) {
    .container {
        max-width: 1150px;
    }
}
```

This is because the `_containers.scss` file does not define container widths for `$xl-media`. I recommend adding a definition for `$xl-media`

P.S. you shouldn't close issues until they're resolved. For example, the issue about jQuery should stay open until the jQuery dependency is deprecated. That is to provide a todo-list to you and your contributors and to prevent other people from accidentally opening an issue about the same thing.
